### ISSUE TITLE
Compatibility with Overflowing Bars

### ISSUE THREAD

**Issue by Cynwale** [Terrails/colorful-hearts#16]
Doesn't change my hearts color with this mod installed, I tried changing the ID (Because I've read that Forge (And maybe Fabric too.) uses Alphabetical Order to arrange mods.) of your mod manually but I'm a complete potato with whatever we're supposed to do with the inside code so of course I've failed.

**Comment by Terrails** [comment]
since the mod also adds its own colored hearts, try to go into their config file and see if it can be disabled. The config files are located inside a config folder in the game directory.

**Comment by Cynwale** [comment]
Thank you for the quick answer, but in the Config Files, there was sadly no way to change it.

I instead followed his advice and made a Resource Pack that changed the Hearts Color.

Sadly, the bars are only one color + base bar color.
