### ISSUE TITLE
loading ResourceLocation class early breaking mixins

### ISSUE THREAD

**Issue by Linguardium** [Terrails/colorful-hearts#17]
https://github.com/Terrails/colorful-hearts/blob/86ca32195a683cb83fe58cadf3a75d4eaf19388b/fabric/src/main/java/terrails/colorfulhearts/fabric/FabMixinPlugin.java#L25C22
Loading your Logger reference here 

will class load your main class, 

https://github.com/Terrails/colorful-hearts/blob/a5ffc190b480a88d2ff532fc666c5117ba43db2f/common/src/main/java/terrails/colorfulhearts/CColorfulHearts.java#L13
which then loads ResourceLocation to set the static field. dont do this.

**Comment by Terrails** [comment]
Should be fixed now. Fetching the logger inside the plugin instead of using a reference from the main class.
