### ISSUE TITLE
Any chance of bringing back the Display mode config?

### ISSUE THREAD

**Issue by Trent2087** [Terrails/colorful-hearts#18]
In health overlay you had a config option for displaying the health numerically. Any Chance of that coming back?
			"display_mode": "OFF",
			/* Text displayed next to health. Minecraft chat color codes are allowed.
			   Available variables:
			       "[HEALTH]": Current health.
			       "[MAX]": Max health.
			       "[HEARTS]": Current health in hearts.
			       "[MAX_HEARTS]": Max health in hearts.
			       "[ROW]": Current health row.
			       "[MAX_ROW]": Max health row.

**Comment by Terrails** [comment]
Unfortunately no. I have decided to not add any more extra features than needed into colorful hearts. I did just add support for overflowing bars' row counter that should give similar behaviour in #20 . Just make sure to disable `allowLayers` for hearts in overflowing bars' config file.
