### ISSUE TITLE
Mislabeled supported versions

### ISSUE THREAD

**Issue by HappyMolly** [Terrails/colorful-hearts#2]
Hello,

This mod is labeled as working on Game versions 1.19—1.19.3 but it requires 1.19.3 to run.

"Failure message: Mod File colorfulhearts-forge-1.19.3-1.0.0.jar needs language provider javafml:44 or above to load"

is it possible to get a version for 1.19.2?

love, Molly

**Comment by Terrails** [comment]
Ah, my bad. Forgot to allow older forge versions. Will have an update up in a bit.
