### ISSUE TITLE
Compatibility for Overflowing Bars By Fuzs ??

### ISSUE THREAD

**Issue by CanecaKun** [Terrails/colorful-hearts#20]
The mentioned mod does the same work as colorful hearts, but with only two colours and with an indicator for the amount of health/armor rows (2x for 20 hearts and so on).
The thing is, when both mods are together the (?x) count stops working for the health, could you maybe work on a config to allow the (x) count to work together with the heart colours from your mod?
In the image below you can see there is a (2x) indicating the armor rows, there should be one on the left side of the health bar as well, but it disappears when colorful hearts is in the modpack. 
![image](https://github.com/Terrails/colorful-hearts/assets/62015531/2eb46a51-8238-4fb4-a12f-49af3d6f840a)

I´m playing on forge 1.20.1 
Thanks!

**Comment by Terrails** [comment]
I have added the support for 1.20.1 and will support it in future release. It should work without any kind of config option on colorful hearts' side. Although I would recommend disabling `allowLayers` for hearts in overflowing bars' config file as it will get rid of any conflicts that could occur. Both mods access the same code which could make overflowing bars override colorful hearts if not disabled. I also log a message whenever `allowLayers` is enabled to inform users about this in the logs.
