### ISSUE TITLE
Crashes my game when launching with the mod on! (Neoforge 1.20.4)

### ISSUE THREAD

**Issue by h3nt41c0m1c5** [Terrails/colorful-hearts#21]
I have done a minecraft server and using the mod would result in the game crashing. Which I find odd but I will put a crash log here!

[crash-2024-03-12_21.45.54-client.txt](https://github.com/Terrails/colorful-hearts/files/14580999/crash-2024-03-12_21.45.54-client.txt)

**Comment by ethan-hann** [comment]
Came here to report the same issue. I just made a mod pack with 100+ mods and went through each one until I found the one crashing my game. Crash log attached.

https://drive.tortal.tech/wl/?id=jndE481BSlbJBRVSc00dk8xfweOkITD4

**Comment by h3nt41c0m1c5** [comment]
Yea I am unsure what is causing the mod freak out but it's bothersome seeing so many hearts on my screen

**Comment by Terrails** [comment]
It should hopefully be fixed in the release I have just uploaded.
