### ISSUE TITLE
[Suggestion] Compatibility with AppleSkin when Hardcore is enabled

### ISSUE THREAD

**Issue by RoyalReject** [Terrails/colorful-hearts#22]
Apple skin has a feature of showing potential health restored while holding food. When in hardcore this breaks and shows normal hearts instead of the hardcore hearts when colorful hearts is enabled. 

Minecraft: 1.20.4
NeoForge: 20.4.200
AppleSkin: 1.20.4-2.5.1
Colorful Hearts: 1.20.4-7.0.2

![2024-03-17_20 57 49](https://github.com/Terrails/colorful-hearts/assets/32550284/7ec1e720-fd2b-41f9-bb32-af7d706a7ee4)

https://github.com/squeek502/AppleSkin/issues/291

**Comment by Terrails** [comment]
Sorry about that. I have noticed the issue a few days ago but completely forgot about it. It should work fine now.
