### ISSUE TITLE
Colorful Hearts Crashes on Neo Forge for Minecraft 1.21 on version 10.0.0

### ISSUE THREAD

**Issue by MatsuKari** [Terrails/colorful-hearts#26]
Minecraft Crashes during the loading phase when Colorful Hearts is installed on Minecraft 1.21 with Neo Forge 
Here is the log:
[crash-2024-06-17_13.11.52-fml.txt](https://github.com/user-attachments/files/15874070/crash-2024-06-17_13.11.52-fml.txt)

**Comment by Terrails** [comment]
Sorry for the delay. There were some issues with Architectury randomly not applying some loader specific code while building the mod. It shoudn't happen in the future anymore.
