### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by Nekohanta** [Terrails/colorful-hearts#28]
I have encountered this problem and I don't understand what is causing it
[crash-2024-06-17_23.24.21-client.txt](https://github.com/user-attachments/files/15875521/crash-2024-06-17_23.24.21-client.txt)

**Comment by Terrails** [comment]
Should be fixed with the latest version now. Something weird happened while compiling the mod.

**Comment by Nekohanta** [comment]
I used the latest version

**Comment by Nekohanta** [comment]
There is no such problem on version 4.1.8
