### ISSUE TITLE
1.21 Armor Bar is levitating whenever i get more health

### ISSUE THREAD

**Issue by makumaku1974** [Terrails/colorful-hearts#29]
![2024-06-22_02 19 07](https://github.com/Terrails/colorful-hearts/assets/129804277/4df24174-d1cb-4fad-94e9-9bb205ba004d)

Just found it weird here since on 1.20.6 it was fine.

**Comment by makumaku1974** [comment]
btw im using health levels

**Comment by Terrails** [comment]
Should be fixed in v10.1.2
