### ISSUE TITLE
Config Changes are Overwritten on Client Load

### ISSUE THREAD

**Issue by StarliteHeart** [Terrails/colorful-hearts#31]
### Mod Loader:
Forge

### Minecraft Version:
1.20.1

### Mod Version:
v4.2.11

### Issue:
After attempting to update the config of Colorful Hearts, the configuration resets to default whenever the client is loaded afterwards. This was originally discovered when attempting to update the array of colors for the additional rows of hearts, but further testing revealed that ALL configuration is reset to default. This is a problem for anyone who might want to use a different palette of colors for their health bars or the different effects.

**Comment by Terrails** [comment]
Should be fixed now
