### ISSUE TITLE
[Potential bug] Can't launch on neoforge

### ISSUE THREAD

**Issue by Darkriders98** [Terrails/colorful-hearts#34]
When using the mod with neoforge, the loading of minecraft after the initialization of all mods takes forever and never launches.

However since neoforge is still in beta version, there may be an issue on their side. It's just that in my custom modpack this is only occuring with this mod, even if it is the only mod activated, so this is not a compatibility issue with another one.

**Comment by Darkriders98** [comment]
I also precise this potential issue is on the 1.21 minecraft version with neoforge - 21.0.91

**Comment by Terrails** [comment]
Yup, there were some breaking changes in the NeoForge config system. It should work with the latest version of the mod now (v10.1.3).
