### ISSUE TITLE
Crashes the game on startup

### ISSUE THREAD

**Issue by James-Fire** [Terrails/colorful-hearts#39]
I am using these mods. I updated things yesterday.

![image](https://github.com/user-attachments/assets/9f1c207d-b776-482d-9bac-47d995d8c805)

![image](https://github.com/user-attachments/assets/1dddc3e2-9b32-41f3-86f4-00690414771e)

If your mod is active, the game crashes on trying to load with the exit message of

![image](https://github.com/user-attachments/assets/e266fead-e1e3-4a05-8c5f-b5825e67b79d)

And this crash log.

[crash-2024-08-13_09.31.12-client.txt](https://github.com/user-attachments/files/16601906/crash-2024-08-13_09.31.12-client.txt)

Disabling your mod prevents the crashes.

**Comment by Terrails** [comment]
update to v10.3.4
