### ISSUE TITLE
[Bug] Crash at launch

### ISSUE THREAD

**Issue by Anonyku05** [Terrails/colorful-hearts#40]
So with the new version of the mod, Fabric 1.20.4, the game will crash after the mods finished loading, here is the crash report:
Launcher: _The game crashed whilst initializing game
Error: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_355 failed_

Latest.log file:
[latest.log](https://github.com/user-attachments/files/16618353/latest.log)

**Comment by Terrails** [comment]
This should be fixed across all versions now. While building the mod it just decided to randomly not create correct refmap files.
