### ISSUE TITLE
[Suggestion] Add option to use vanilla team color as heart color

### ISSUE THREAD

**Issue by Wlnfr** [Terrails/colorful-hearts#43]
Basically the title, add a config option like `Use Team Color = true/false`. In addition to settings hearts to team color, with it enabled render text `Current Health/Max Health` near the hearts either if a player has more than 10 hearts or just at all time, since all hearts should be of the same color.

**Comment by Terrails** [comment]
I do not have any intention of adding extra features to this mod besides for compatibility, so that is unfortunately a no.
