### ISSUE TITLE
Properly declare as a client mod via the file's game versions

### ISSUE THREAD

**Issue by aronjanosch** [Terrails/colorful-hearts#5]
Colorful-hears gets downladed by https://github.com/itzg/docker-minecraft-server
The docs mentiots that mods properly declare as a client mod via the file's game versions to avoid this issue.

https://docker-minecraft-server.readthedocs.io/en/latest/types-and-platforms/mod-platforms/auto-curseforge/#exclude-client-mods

**Comment by Terrails** [comment]
My bad, I forgot to mark the latest version files as such. I've marked the files as client only now. It might take some time for the change to sync through curseforge.

**Comment by aronjanosch** [comment]
Thanks <3
