### ISSUE TITLE
Crashing on Modded Instance

### ISSUE THREAD

**Issue by thrasos-dev** [Terrails/colorful-hearts#6]
I am crashing on an instance of around 230 mods. The crash occurs upon joining the world. Let me know if you need any more details.

[crash-2023-10-02_20.14.17-client.txt](https://github.com/Terrails/colorful-hearts/files/12785271/crash-2023-10-02_20.14.17-client.txt)

**Comment by thrasos-dev** [comment]
Some more info...

I am running:
- Fabric 1.20.1
- Mod version: [Fabric] 1.20.1-v4.0.1

**Comment by Terrails** [comment]
The issue is related to a mixin in the Frostiful mod. I have opened an issue there.
